### ISSUE TITLE
input bug

### ISSUE THREAD

**Issue by RetardedDev** [iliis/crossword#1]
On pc when you execute main.py and press  return the game breaks

**Comment by iliis** [comment]
I cannot recreate this on my PC. Can you post the traceback? And also the contents of the puzzle.log file?

**Comment by RetardedDev** [comment]
of course

**Comment by iliis** [comment]
Any updates? Or can I close this?

**Comment by iliis** [comment]
Without further information I cannot debug this. Feel free to reopen this issue if you can reproduce it ;P
