### ISSUE TITLE
Textbox popup message delay

### ISSUE THREAD

**Issue by magicdominic** [iliis/crossword#14]
There is a random delay of over 10s when sending a textbox message before it appears. Cause still unknown. More testing required.

**Comment by iliis** [comment]
Cannot reproduce. Tested with `send_popup.py` from commit 13c4a9edc5b072d262c5c8a72fc9b06852afadb5.

**Comment by iliis** [comment]
The issue probably lies with TouchDesigner. Maybe there is some line-buffering or something involved?

**Comment by iliis** [comment]
Da das offebar na aktuell isch machis mal widr uf.

**Comment by iliis** [comment]
Swär praktisch es Wireshark-Log zha vomne Fall wo de Delay uftritt (und am beste es zweits wos nid uftritt, z.B. vomne andere Kommando). Was gnau für e Python-Version bruchsch du eich?

Wasd susch auna chasch probiere isch dBuffer-Size hie https://github.com/iliis/crossword/blob/master/management_interface.py#L134 uf öppis vil chliners (oder grössers) zsetze. Ich glaub zwar nid dass das sProblem isch, aber wer weiss...

**Comment by magicdominic** [comment]
Wenn nach einem Spiel das Crossword nur mit reset zurückgesetzt wird erhalten wird das delay von messages wie hier aufgezeichnet. wenn jedoch mit quit neu gestartet wird ist das delay nicht da beim ersten spiel. 

[delay_wireshark](https://user-images.githubusercontent.com/2743621/50383347-12bf8f00-06b2-11e9-8563-1d263e5ffbae.PNG)

[wireshark_msg_display_delay_debug.zip](https://github.com/iliis/crossword/files/2705954/wireshark_msg_display_delay_debug.zip)

[puzzle.log](https://github.com/iliis/crossword/files/2705963/puzzle.log)

**Comment by iliis** [comment]
Danke, das isch sehr hilfriich! Leider ischs puzzle.log nid vollständig und de entscheidend Moment isch nüm drin. Chaschmer das namal schicke und sicher stelle dass de Ziitpunkt vom Dec 23, 2018 12:48:52.538136000 CET enthalte isch? Alles wo mindschdens e Stund oderso älter als das isch chasch ja uselösche.

Ich han allerdings tatsächlich na en Bug gfunde (sogar zwei, aber de ander isch harmlos): Wennt schnell gnueg Packet sendisch chas si dass mehreri ufs Mal achömed und denn wird nur eis bearbeitet. Wenn du also dauernd 'get_time' pollsch chas sii dass s Popup-Kommando undergaht und ersch usgfüert wird wennt snegtscht mal 'get_time' schicksch. Probier mal die aktuell revision und lueg öbs jetzt gfixt isch.

**Comment by magicdominic** [comment]
tested, works yeah!
