### ISSUE TITLE
save state 

### ISSUE THREAD

**Issue by magicdominic** [iliis/crossword#15]
save the state of all entered crossword letters and load these upon restart of app.
add option to reset to default.

**Comment by iliis** [comment]
Implemented in commit e1e931ef93f837e798a8b40c081d9127f71410e9
Currently, only the puzzle state (input of crossword and if solved) and remaining time is stored.

Open Questions:
- [x] Should remaining time be stored as _time left_ (i.e. pausing the timer when app is not running) or as an absolute _timestamp_ (and therefore continue the timer even when no code is running)?
- [x] In which cases is the backup not required? Currently, the only situation that does _not_ cause a restore-promt is when the game timer has run out and the final screen is/was shown.
- [ ] Currently, state is stored _very often_ (whenever the input of the puzzle changes!). This might tire the harddrive a bit too fast...

**Comment by magicdominic** [comment]
-time left shoudl be used (pausing time in case of reset/problems)
-restore promt: special case "nothing typed" (except default letters) should not result in restore prompt upon reset. (programm should be able to reset multiple times in case of abortet start or starting twice)
-storing: only store correct words => less IO but still all data that players need

**Comment by iliis** [comment]
Eich chömmer das au uf Dütsch diskutiere, wär ja nid so als würs öpper anders intressiere xD

- Time left: Isch bereits so.
- Es frägt jetzt nurna öbd wotsch widerherstelle wenn au würkli was gänderet worde isch.
- Nur die korrekte Wörter speichere findi problematisch: Entweder verlürsch partielli Lösige oder du kriegsch Informatione wod susch nid kriegsch. Usserdem ischs vilich chli verwirrend. Nett wär wohl wennts du vom Controll-Ruum us chönntisch restore.

**Comment by iliis** [comment]
Restore chasch jetzt nurna remote. Git weniger verwirrti Benutzer ;) Susch isch das abghandlet würi sege.
